version: '3.8'

services:

  student-frontend:
    container_name: student-frontend
    build:
        context: .
        dockerfile: frontend/Dockerfile
    ports:
        - 3000:3000

  student-service:
    container_name: student-service
    build:
      context: .
      dockerfile: student-service/Dockerfile
    depends_on:
      - student-database
    environment:
        - "DATABASE_URL=jdbc:mysql://student-database/student_management?useSSL=false"
        - "DATABASE_USER=root"
        - "DATABASE_PASSWORD=root"
    ports:
      - 8080:8080

  student-database:
    container_name: student-database

    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./db-scripts/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql